{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-bukkit-1.20.1",
    "version": "1.0.0-alpha.2-bukkit-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GaoShiLib-bukkit-1.20.1-1.0.0-alpha.2-bukkit-mc1.20.1-dev.jar",
          "url": "GaoShiLib-bukkit-1.20.1-1.0.0-alpha.2-bukkit-mc1.20.1-dev.jar",
          "size": 1983,
          "sha512": "b54c7b265550a5f773be57ebe07c5b9e5ed2c88728ef387ec66a072e07ba3667ceec053ff18565876fd3f9f9f7520617e85673daf54c5c5a63c10188fbe22046",
          "sha256": "f59f5bd71b17ad57e5ded55cfb9c87edc64658b31d79755e44b09e022ba6c21c",
          "sha1": "3a75e6ca8a37e152d32bcd783495ee4c1a3d381e",
          "md5": "49cf900915eb42fea7544743aac7079d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-bukkit-1.20.1-1.0.0-alpha.2-bukkit-mc1.20.1-dev.jar",
          "url": "GaoShiLib-bukkit-1.20.1-1.0.0-alpha.2-bukkit-mc1.20.1-dev.jar",
          "size": 1983,
          "sha512": "b54c7b265550a5f773be57ebe07c5b9e5ed2c88728ef387ec66a072e07ba3667ceec053ff18565876fd3f9f9f7520617e85673daf54c5c5a63c10188fbe22046",
          "sha256": "f59f5bd71b17ad57e5ded55cfb9c87edc64658b31d79755e44b09e022ba6c21c",
          "sha1": "3a75e6ca8a37e152d32bcd783495ee4c1a3d381e",
          "md5": "49cf900915eb42fea7544743aac7079d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-bukkit-1.20.1-1.0.0-alpha.2-bukkit-mc1.20.1-sources.jar",
          "url": "GaoShiLib-bukkit-1.20.1-1.0.0-alpha.2-bukkit-mc1.20.1-sources.jar",
          "size": 1698,
          "sha512": "0a0c8147eb73d4dfdb019b1d8fd09d089f772f84d2e5d2aa7ab9f3bf3d00039a12d64d9db66335dca88f3d753059446c771fccb2cc183eb5254f1af1da9c2b89",
          "sha256": "1795899daf2d3d07684b7755633bd133440564ada7bb81f0830850f108196fe5",
          "sha1": "40719adf5fde24d791c3da9284c9bc4817db05ea",
          "md5": "b754983a17300302b57a051522e96d1a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-bukkit-1.20.1-1.0.0-alpha.2-bukkit-mc1.20.1-dev-all.jar",
          "url": "GaoShiLib-bukkit-1.20.1-1.0.0-alpha.2-bukkit-mc1.20.1-dev-all.jar",
          "size": 21347,
          "sha512": "34b5f6b8be2e23726794eeec8b061c9c71cc996f9e0cb16d8e76b27d0115a7eca4a80e8ae91ca8f46a75bb0e8df53c2d66a3e81fa1f8bf7d092e6a8da54642ea",
          "sha256": "5687b567121488cff53daf2b6417c318b83cccb3ddae67e77fb7392b21115cd8",
          "sha1": "4a176e7fe77b07053bdc1b75d0b633753f6df0eb",
          "md5": "584c78e2690b997de95ea58a61f44c12"
        }
      ]
    }
  ]
}
