{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-velocity-1.20.1",
    "version": "1.0.0-alpha.2-velocity-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1.jar",
          "url": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1.jar",
          "size": 2082,
          "sha512": "8404f57dcbc76514278644d3f1daa1f131a7d63c88b0d8e4b9fe78fa3593e15868b3227c0d82580adefb6035da3f478ffdf7f5b7bbe2322a2ccafa2281990397",
          "sha256": "9ff3ea026c45b2fb0e34e69763813a10f6c7086b2f67cb4b4841380fc86ba766",
          "sha1": "1adafdaedb595162acbf4ff09ad5f5d27daa75bf",
          "md5": "5aff7278397a4e1d1952c888354ef868"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1.jar",
          "url": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1.jar",
          "size": 2082,
          "sha512": "8404f57dcbc76514278644d3f1daa1f131a7d63c88b0d8e4b9fe78fa3593e15868b3227c0d82580adefb6035da3f478ffdf7f5b7bbe2322a2ccafa2281990397",
          "sha256": "9ff3ea026c45b2fb0e34e69763813a10f6c7086b2f67cb4b4841380fc86ba766",
          "sha1": "1adafdaedb595162acbf4ff09ad5f5d27daa75bf",
          "md5": "5aff7278397a4e1d1952c888354ef868"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1-sources.jar",
          "url": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1-sources.jar",
          "size": 1538,
          "sha512": "59c4386578f7073d70ad44cc339c76d4e960852a6a6565d7838240a43d6207fe400f319e367eb8154ea654d52c3823ac864d087286a316596f9655d44aec9ab6",
          "sha256": "d99e9ceecef16076441bb97b40dfed8adf60771f9d66b7c6566c860307129336",
          "sha1": "20bf1815f803321c0eeb9de90446cea2dc7178d9",
          "md5": "8a38306cd59e95cf2b3d966423b3aa3d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1-all.jar",
          "url": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1-all.jar",
          "size": 21446,
          "sha512": "946f14fec6af46e5929c84d1852845afe8999baec3e730fbcd8b8f05a547f94f87ea2ba8be984f769c989cba9b0c33ee5ef661ef05be8758452fec2dac969ab6",
          "sha256": "76dd2bf3fc5c38473931ee8a3bcd5789a660bdfc4a7a7d65b629cffca2b8d51f",
          "sha1": "5f45554131e00b175b6cade09c9925b6f50feb30",
          "md5": "3805fd269118f9d1a8c36b74543b1672"
        }
      ]
    }
  ]
}
