{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-velocity-1.20.1",
    "version": "1.0.0-alpha.2-velocity-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1.jar",
          "url": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1.jar",
          "size": 2082,
          "sha512": "b0c960650adf0b1126d14f87d72b0773c61b770172ba221b9f18169d6f0a247024a4e76f02ec49df9b1467c63c79e4ab73e1a5f3dac92e5aca6ada0f4653eef4",
          "sha256": "aa2e0fd381b3980991616c5e7dc77f4927409ae8a22ce529a62f7fcb21f2a9ec",
          "sha1": "05c2f07d2b1cee590a2db11892b748f413c5ac2d",
          "md5": "90873d68aa796f82c184cd2ee1a9ee59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1.jar",
          "url": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1.jar",
          "size": 2082,
          "sha512": "b0c960650adf0b1126d14f87d72b0773c61b770172ba221b9f18169d6f0a247024a4e76f02ec49df9b1467c63c79e4ab73e1a5f3dac92e5aca6ada0f4653eef4",
          "sha256": "aa2e0fd381b3980991616c5e7dc77f4927409ae8a22ce529a62f7fcb21f2a9ec",
          "sha1": "05c2f07d2b1cee590a2db11892b748f413c5ac2d",
          "md5": "90873d68aa796f82c184cd2ee1a9ee59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1-sources.jar",
          "url": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1-sources.jar",
          "size": 1538,
          "sha512": "66b2f770a630f4e010064a65b51e3837c97f027ee30cb9c42a3bcf207d78b4ac14da5287f1f77b8b1aee01e731fc4409149644dc4e3464b87e3a0530512ec7ec",
          "sha256": "0d37b6719b28fbb08995b618ec8f789d74a76abfb32fb61937691a0ab59b6821",
          "sha1": "7782167b57351bc0e0e7acc36ca9214f50ed1618",
          "md5": "69506c92b00a2194f94a1760e745cf0b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1-all.jar",
          "url": "GaoShiLib-velocity-1.20.1-1.0.0-alpha.2-velocity-mc1.20.1-all.jar",
          "size": 21446,
          "sha512": "be452f7020088998511b4cba87d34c657ea68fe403722fcc88b3587d1ab6b260659d623e5858f33583ea6e883533f6738b654c396d2be18caf4cce4aa68a6424",
          "sha256": "17f1002e44c638aaf3b756dc29947c49b6937d13d88e0da319bf6cd1e6480a5a",
          "sha1": "43ab72d6bbc028c7652fa84d80f884c43895e7ba",
          "md5": "0b84496d02873f41b962f61d4c05ee97"
        }
      ]
    }
  ]
}
