{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-fabric-1.20.1",
    "version": "1.0.0-alpha.2-fabric-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.2-fabric-mc1.20.1.jar",
          "url": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.2-fabric-mc1.20.1.jar",
          "size": 75664,
          "sha512": "c0408d4fed00e310f03aee17ea2a4a5ae090cee0744f0a7953277cd380fae36431e78332211af5db7f58078412971dcba28b9b4a7783ef548c8cc9faa5449e88",
          "sha256": "2ca2faa069a1bced55e8ae21d5e91d87fe7add59743c6386d7306ce2c69f6b37",
          "sha1": "445f4ed6bfb1d9d025f5dd7f84e5b15ae3edea75",
          "md5": "0a622117fae53e8c66b308f95a8998df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.2-fabric-mc1.20.1.jar",
          "url": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.2-fabric-mc1.20.1.jar",
          "size": 75664,
          "sha512": "c0408d4fed00e310f03aee17ea2a4a5ae090cee0744f0a7953277cd380fae36431e78332211af5db7f58078412971dcba28b9b4a7783ef548c8cc9faa5449e88",
          "sha256": "2ca2faa069a1bced55e8ae21d5e91d87fe7add59743c6386d7306ce2c69f6b37",
          "sha1": "445f4ed6bfb1d9d025f5dd7f84e5b15ae3edea75",
          "md5": "0a622117fae53e8c66b308f95a8998df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.2-fabric-mc1.20.1-sources.jar",
          "url": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.2-fabric-mc1.20.1-sources.jar",
          "size": 34616,
          "sha512": "2f980014f8b02badd852e27614dbb7e58aabfe78b7439fa18caf9866383f93707b9d88a3ec07db4273cf0cbc95fb00a0c26f9602d56a2389286831e46f10b42c",
          "sha256": "46bc3c9d1668b989c959b5b645480e25b5df3974f3a36f02e958b07b3faed6c3",
          "sha1": "1f62df1c99df843021d224a445944d94ac93f251",
          "md5": "71e63a08a28659d8512452278bfa94a5"
        }
      ]
    }
  ]
}
