{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-forge-1.20.1",
    "version": "1.0.0-alpha.2-forge-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-forge-1.20.1-1.0.0-alpha.2-forge-mc1.20.1.jar",
          "url": "GaoShiLib-forge-1.20.1-1.0.0-alpha.2-forge-mc1.20.1.jar",
          "size": 74649,
          "sha512": "92c42177bac319e0ec36481ca26a8866cf7c49f0baa29ca9332ea52a4453f7d2e8b02a4d8987f358a7e95954ea3ba662c8792b9249b564ec8aa1d37d557c8628",
          "sha256": "396814a4876a17ceb4730db3bf4f40bf9c49425ce785544dccddba9c2f8b2d32",
          "sha1": "f92f1faee8ab166c5d2b9bb1dc4611a3660e7e7b",
          "md5": "3bd587fac5b0c8496201e7da8dbee08f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-forge-1.20.1-1.0.0-alpha.2-forge-mc1.20.1.jar",
          "url": "GaoShiLib-forge-1.20.1-1.0.0-alpha.2-forge-mc1.20.1.jar",
          "size": 74649,
          "sha512": "92c42177bac319e0ec36481ca26a8866cf7c49f0baa29ca9332ea52a4453f7d2e8b02a4d8987f358a7e95954ea3ba662c8792b9249b564ec8aa1d37d557c8628",
          "sha256": "396814a4876a17ceb4730db3bf4f40bf9c49425ce785544dccddba9c2f8b2d32",
          "sha1": "f92f1faee8ab166c5d2b9bb1dc4611a3660e7e7b",
          "md5": "3bd587fac5b0c8496201e7da8dbee08f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-forge-1.20.1-1.0.0-alpha.2-forge-mc1.20.1-sources.jar",
          "url": "GaoShiLib-forge-1.20.1-1.0.0-alpha.2-forge-mc1.20.1-sources.jar",
          "size": 33406,
          "sha512": "26603f7fb03fcbe58d45ad04e62b81a7dff3b07881ce320850690a9615ff95c1e837d5afa531b5aec4bf64ad4a9fcdda8e1e2347cecc55bc4b26d10e0ba7a148",
          "sha256": "2ec27c13db063ba7da8fa62e7ff7377836749d39a0d83180c4204b632f07e020",
          "sha1": "247be98fa360c0c664c03c668d8a0ea00a66da27",
          "md5": "70986486f46dd1618d403b80af06a03a"
        }
      ]
    }
  ]
}
