{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-xplat-1.20.1",
    "version": "1.0.0-alpha.1-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-api",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.1-mc1.20.1.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.1-mc1.20.1.jar",
          "size": 35413,
          "sha512": "5414d4622931e44c9f552af1e2129e138778b1fa49ce11c78f3f98bcb6fefe11a70b6614297303d7507a5e5b743985c77f50c464a820d3993e9a837d64f93cdb",
          "sha256": "0865d0943d67e578106f5af55f49b8c5323d531731c47b02bedbde7e0becafff",
          "sha1": "d8dec9269d146ae1a7c903cae1bb7b64e1e1f146",
          "md5": "297891e05e955df84420a28bfd8f39b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-api",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "ho-library",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.1-mc1.20.1.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.1-mc1.20.1.jar",
          "size": 35413,
          "sha512": "5414d4622931e44c9f552af1e2129e138778b1fa49ce11c78f3f98bcb6fefe11a70b6614297303d7507a5e5b743985c77f50c464a820d3993e9a837d64f93cdb",
          "sha256": "0865d0943d67e578106f5af55f49b8c5323d531731c47b02bedbde7e0becafff",
          "sha1": "d8dec9269d146ae1a7c903cae1bb7b64e1e1f146",
          "md5": "297891e05e955df84420a28bfd8f39b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.1-mc1.20.1-sources.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.1-mc1.20.1-sources.jar",
          "size": 30555,
          "sha512": "09e3fdeacc29ff8087ded188401bfb93dc2e123cb91867155f1ac08b8cd98078b43b854469ad98c7bbef218ad05ffaf2f38f08215bb1d8176833c07f97999a1e",
          "sha256": "54b49cb06184d7c9581e2682a744609247106106d538e06375c8a672c68914fc",
          "sha1": "c36bb3b09507261d85e7616a6356e5edc3b320b4",
          "md5": "445a364a6521b5027206ac10f2f32164"
        }
      ]
    }
  ]
}
