{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-fabric-1.20.1",
    "version": "1.0.0-alpha.1-fabric-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.1-fabric-mc1.20.1.jar",
          "url": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.1-fabric-mc1.20.1.jar",
          "size": 75202,
          "sha512": "1cd7d6cb5e10f6054231688bff2c43afb3839691cc9965c462150868e7df0f53fed3ea93e1dd0a53387dfde5eea280ad2707938375e8f5ac61cef86d8f319cb1",
          "sha256": "d5fd97a8af2f6141923e49924566b37f298e6bc16b53a4ba83ab8c59af4831a0",
          "sha1": "2bb5c4fe473e920c471dc06c32d7e382ef7ca11e",
          "md5": "fcc6b3680bf3d875e7f9f09a511caf8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.1-fabric-mc1.20.1.jar",
          "url": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.1-fabric-mc1.20.1.jar",
          "size": 75202,
          "sha512": "1cd7d6cb5e10f6054231688bff2c43afb3839691cc9965c462150868e7df0f53fed3ea93e1dd0a53387dfde5eea280ad2707938375e8f5ac61cef86d8f319cb1",
          "sha256": "d5fd97a8af2f6141923e49924566b37f298e6bc16b53a4ba83ab8c59af4831a0",
          "sha1": "2bb5c4fe473e920c471dc06c32d7e382ef7ca11e",
          "md5": "fcc6b3680bf3d875e7f9f09a511caf8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.1-fabric-mc1.20.1-sources.jar",
          "url": "GaoShiLib-fabric-1.20.1-1.0.0-alpha.1-fabric-mc1.20.1-sources.jar",
          "size": 34410,
          "sha512": "a7619b6e2acfbf6076c380ad11863d1004ad9418d352aa1d35a5e52ace1765064189d534c50b6cd870a051e4b94e106a0921048d355d773352482cca40c6bc85",
          "sha256": "2a99f7480b0ceb5e9e801b789d194a45e888b15576dcc3cc8b9760cafc4b1a90",
          "sha1": "b76879640a9975c976983feb5b73110180fa2acb",
          "md5": "14947d356138505b910805a37d9baad9"
        }
      ]
    }
  ]
}
