{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-sponge-1.20.1",
    "version": "1.0.0-alpha.2-sponge-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GaoShiLib-sponge-1.20.1-1.0.0-alpha.2-sponge-mc1.20.1.jar",
          "url": "GaoShiLib-sponge-1.20.1-1.0.0-alpha.2-sponge-mc1.20.1.jar",
          "size": 2050,
          "sha512": "7464a9e25863554c13cb99ec74f873773f53bad68a199883506f9c2098524da86f0979e49a12f1a9b6062dc80183dd616dbc2f57c8f4bd09e60cbf1635a62b6e",
          "sha256": "38d9e2fbba7bf30d4273aef8e25c94fce5b001ad528409a1822d8cc56bd4dcf3",
          "sha1": "884ef39c5bba8268d5a657230061eea55adcf1b5",
          "md5": "ddb33e20b7eb3464ba93f3c8eede407c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "spongeapi",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-sponge-1.20.1-1.0.0-alpha.2-sponge-mc1.20.1.jar",
          "url": "GaoShiLib-sponge-1.20.1-1.0.0-alpha.2-sponge-mc1.20.1.jar",
          "size": 2050,
          "sha512": "7464a9e25863554c13cb99ec74f873773f53bad68a199883506f9c2098524da86f0979e49a12f1a9b6062dc80183dd616dbc2f57c8f4bd09e60cbf1635a62b6e",
          "sha256": "38d9e2fbba7bf30d4273aef8e25c94fce5b001ad528409a1822d8cc56bd4dcf3",
          "sha1": "884ef39c5bba8268d5a657230061eea55adcf1b5",
          "md5": "ddb33e20b7eb3464ba93f3c8eede407c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-sponge-1.20.1-1.0.0-alpha.2-sponge-mc1.20.1-sources.jar",
          "url": "GaoShiLib-sponge-1.20.1-1.0.0-alpha.2-sponge-mc1.20.1-sources.jar",
          "size": 1750,
          "sha512": "802e574481ed65a9a48d19f306b66e64817c6bc9bc4dbfa935ca71117fde27431bde01dbd92087342ac73f9b1f05a6b0897f43b4f237d335e4b37a19bce32ad5",
          "sha256": "3dd2852990c67a4c668a8cf4fa7fd401c3fbb4102778dd737be4b5d5e3a8a8a8",
          "sha1": "3cacacaa4c69645e902bbc93e90cb46ec1f609a2",
          "md5": "0823e45b761db489fbbb60d2c01c9f83"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-sponge-1.20.1-1.0.0-alpha.2-sponge-mc1.20.1-all.jar",
          "url": "GaoShiLib-sponge-1.20.1-1.0.0-alpha.2-sponge-mc1.20.1-all.jar",
          "size": 10055901,
          "sha512": "92df5055e94cef05865245f93ce4170869a08ecc2cf6a45c6d7f5c892ee4cc86b611e592d04050eaa68718e9937ced3198b5e07453350b044e96f75afcd09c3f",
          "sha256": "5b2a2002c3549de31a37cc36926e3336cef118a37203af9f87ecbaba80df2cbd",
          "sha1": "9abb6b1556da86447c52d9e8ae10eaa7e675197c",
          "md5": "fb0a1ab32ee97547c1d297459983596c"
        }
      ]
    }
  ]
}
