{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-quilt-1.20.1",
    "version": "1.0.0-alpha.2-quilt-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.quiltmc.quilted-fabric-api",
          "module": "quilted-fabric-api",
          "version": {
            "requires": "7.2.1+0.88.0-1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-quilt-1.20.1-1.0.0-alpha.2-quilt-mc1.20.1.jar",
          "url": "GaoShiLib-quilt-1.20.1-1.0.0-alpha.2-quilt-mc1.20.1.jar",
          "size": 75681,
          "sha512": "2faa133330169b241b8e01247ce940888941e2e40f063c84ac5ed88a9db00a71896ac28e3d15f40d0709ea3ae268e71320e569f4d37227c2a3d161787ddcdbd0",
          "sha256": "6148ea4fdc8560e82aaf66b7cd480ea6087196e10f4cf6a52c94394c1b293ffb",
          "sha1": "21cdf68419e163ec7b51c75c9bcf098288924c2e",
          "md5": "e985b2c2d22e653d1b20d5a9b11bef6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.quiltmc.quilted-fabric-api",
          "module": "quilted-fabric-api",
          "version": {
            "requires": "7.2.1+0.88.0-1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        },
        {
          "group": "org.quiltmc",
          "module": "quilt-loader",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-quilt-1.20.1-1.0.0-alpha.2-quilt-mc1.20.1.jar",
          "url": "GaoShiLib-quilt-1.20.1-1.0.0-alpha.2-quilt-mc1.20.1.jar",
          "size": 75681,
          "sha512": "2faa133330169b241b8e01247ce940888941e2e40f063c84ac5ed88a9db00a71896ac28e3d15f40d0709ea3ae268e71320e569f4d37227c2a3d161787ddcdbd0",
          "sha256": "6148ea4fdc8560e82aaf66b7cd480ea6087196e10f4cf6a52c94394c1b293ffb",
          "sha1": "21cdf68419e163ec7b51c75c9bcf098288924c2e",
          "md5": "e985b2c2d22e653d1b20d5a9b11bef6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-quilt-1.20.1-1.0.0-alpha.2-quilt-mc1.20.1-sources.jar",
          "url": "GaoShiLib-quilt-1.20.1-1.0.0-alpha.2-quilt-mc1.20.1-sources.jar",
          "size": 32951,
          "sha512": "121ec84952e5d030ab43028f5f0bd311b65df1eaeb6f8aec5424856e36c8f0d4c475aad16da7a2f72fbb5181de693b022766a1c8f7f459b1425303af9c78ddfa",
          "sha256": "a0382b21e377f67e81d45beb79ed2d7a987d2dcef50942f19ddd4960b7d7edd5",
          "sha1": "3c546f68542372d569afee428b7d5f36973e560e",
          "md5": "23c3d9ab0bc3dbe9c977e4094a8f3e2d"
        }
      ]
    }
  ]
}
