{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-bungeecord-1.20.1",
    "version": "1.0.0-alpha.2-bungeecord-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1.jar",
          "url": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1.jar",
          "size": 2174,
          "sha512": "07c2deca43384ca43eea334832dcffc0dc714ce15c86321663691deb3d971012ceb29ea449e1dfbe297074470b98f13cd48c26f8128bcfaa2c0e2cce3c08c682",
          "sha256": "e334db6c1a4b7ab117cad6106cc69a56c05f42b3d4ba07ebb4c443d67260ae3a",
          "sha1": "0ba700051561b58fb96271c2d5e1d63fbf2e6265",
          "md5": "357c89c5a5cdf82ccbaa6adfd072d384"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1.jar",
          "url": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1.jar",
          "size": 2174,
          "sha512": "07c2deca43384ca43eea334832dcffc0dc714ce15c86321663691deb3d971012ceb29ea449e1dfbe297074470b98f13cd48c26f8128bcfaa2c0e2cce3c08c682",
          "sha256": "e334db6c1a4b7ab117cad6106cc69a56c05f42b3d4ba07ebb4c443d67260ae3a",
          "sha1": "0ba700051561b58fb96271c2d5e1d63fbf2e6265",
          "md5": "357c89c5a5cdf82ccbaa6adfd072d384"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1-sources.jar",
          "url": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1-sources.jar",
          "size": 1817,
          "sha512": "e0e52e84c95e8feaeec2a1c5f5cdd3019532cd16657c53561a33739c75ee9ebf75a20cf7d6901b81ec649ccee6e6b3026ede72a9686374a1654a837a3650de9b",
          "sha256": "a7142680e6a672221adc1982e5a1248b2d93afd8a9386b4761c85aa5838e35c6",
          "sha1": "fa63c2ec6146aedcf1581977b8ec213c188079b2",
          "md5": "13064d2d783f736f4b60d2f39e671e0a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1-all.jar",
          "url": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1-all.jar",
          "size": 21538,
          "sha512": "9a11c56778fdb3a359600085d899f9a1bd02f211fd24f8b5aceb34a158ae88c7059107d2286134c38b211eb231a8015b0522259935772401f277a9f25b677fa9",
          "sha256": "789f340f099e0fbd5b096eb29a2c2018df93f56492e318ef9280ed3c5ded3ad0",
          "sha1": "e5beab46e6393b650aa61ce466f8ff390967a4fb",
          "md5": "4bd1f1b8021f75e15c7de4c0d49a3bca"
        }
      ]
    }
  ]
}
