{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-bungeecord-1.20.1",
    "version": "1.0.0-alpha.2-bungeecord-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1.jar",
          "url": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1.jar",
          "size": 2174,
          "sha512": "38e8782f1398ec12d9737b8f180ce9136e86e4970e0aff8e9338e766f4d252471f44f7a7a6a689fd3b21bf870c3404f199685ffbe8f043064069d3d08b694010",
          "sha256": "8334d77dfb86ba78be605dabb68e5dfd904c18b6917526a754e9729025706110",
          "sha1": "e76c5363340c33cbdb73e2b740496d29e758b51c",
          "md5": "f84cec3ad495b553fb0b6cf862b8817f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1.jar",
          "url": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1.jar",
          "size": 2174,
          "sha512": "38e8782f1398ec12d9737b8f180ce9136e86e4970e0aff8e9338e766f4d252471f44f7a7a6a689fd3b21bf870c3404f199685ffbe8f043064069d3d08b694010",
          "sha256": "8334d77dfb86ba78be605dabb68e5dfd904c18b6917526a754e9729025706110",
          "sha1": "e76c5363340c33cbdb73e2b740496d29e758b51c",
          "md5": "f84cec3ad495b553fb0b6cf862b8817f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1-sources.jar",
          "url": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1-sources.jar",
          "size": 1817,
          "sha512": "a09ef07cec1120c721a6ec29908d3b3ffa1fe9059617f0efe7d537aa33e6a8778225c95405b652436bb4e026d754adc71a4cdfc521d7e9248a577d8abd7b97cb",
          "sha256": "e70c9875796a1b172ddf9815cf3638434ccf451b91255436df6349a03346d77f",
          "sha1": "0c82ec72730b57d1598b8dc03eae1f047323f82d",
          "md5": "8ef0fcfdd36dd13b16a4f6713f1568c9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1-all.jar",
          "url": "GaoShiLib-bungeecord-1.20.1-1.0.0-alpha.2-bungeecord-mc1.20.1-all.jar",
          "size": 21538,
          "sha512": "a13e5c972fd42e81f1a1b6c1bbfbaacd7a54533b569dc058476ded491d1bb517d9c8e384d4eb61c8f96d7b1bd495e0fdb99072faed54b664fc068d2e458b7a2a",
          "sha256": "0729e5ccb2a30a7841704e40242df6f2224393681d8ebbc0f19432d7dfd9e845",
          "sha1": "ba8fa2b43ae725ea365ad4193b58d601f28e7351",
          "md5": "7b96f7553fc7bcfe5fe0fa71721c1b8a"
        }
      ]
    }
  ]
}
