{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-xplat-1.20.1",
    "version": "1.0.0-alpha.2-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-api",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1.jar",
          "size": 35883,
          "sha512": "b679e605dcd85d27a42a2f36f301efdda9dd8e32dd90502cddf1e98aa3057c670ca505abc45de93b3372d970f2c14368cfa04c7df57a51f13b2b22255d52d623",
          "sha256": "ed57355c0195516fc8907ef5365d0b0c2c4551294211b672c89fb5302ec5cf61",
          "sha1": "15646f386528db175eb9dfe060848d2ad5055ef2",
          "md5": "16539514cac41cf562adfb760c9d89f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-api",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "ho-library",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1.jar",
          "size": 35883,
          "sha512": "b679e605dcd85d27a42a2f36f301efdda9dd8e32dd90502cddf1e98aa3057c670ca505abc45de93b3372d970f2c14368cfa04c7df57a51f13b2b22255d52d623",
          "sha256": "ed57355c0195516fc8907ef5365d0b0c2c4551294211b672c89fb5302ec5cf61",
          "sha1": "15646f386528db175eb9dfe060848d2ad5055ef2",
          "md5": "16539514cac41cf562adfb760c9d89f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1-sources.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1-sources.jar",
          "size": 30769,
          "sha512": "ec99e0cfc40d5de61c5e06a35cff0c4b298febb8c9e43ad4a6f32c671738ce8eae109ab7a1df3f19e915ce2d2ad0979e3df1c3b997a8e2d207fc71acd2f35420",
          "sha256": "616d36455fc0b41d27924573a339174d86799709784667df519cb5194b3ec255",
          "sha1": "4e7d36d69c737b92f924d39f6785fb89ba2a90bc",
          "md5": "2508d1d435390260c41a963764e17c36"
        }
      ]
    }
  ]
}
