{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.mrcraftteammc.gaoshilib",
    "module": "GaoShiLib-xplat-1.20.1",
    "version": "1.0.0-alpha.2-mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-api",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1.jar",
          "size": 35883,
          "sha512": "516ba3bbfc32eb7a6a7c8b369cbc5bd0ce8f86822666ec5053c640f9e2682e835db35573fc723d3a1137139deb52a99eb55b9850cdbac44de7f1c01505c7cc63",
          "sha256": "09888e05c11b7ce6c51a7090f7594c0b5694595fdcfbadfabc11d7f92cb57d8d",
          "sha1": "3053dfe82bde53616606f3198581a3e05bcfdbc1",
          "md5": "f602de05fd5de2296fa433e4500167d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-api",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.github.Fallen-Breath",
          "module": "conditional-mixin",
          "version": {
            "requires": "v0.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "fabric-loader"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "ho-library",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1.jar",
          "size": 35883,
          "sha512": "516ba3bbfc32eb7a6a7c8b369cbc5bd0ce8f86822666ec5053c640f9e2682e835db35573fc723d3a1137139deb52a99eb55b9850cdbac44de7f1c01505c7cc63",
          "sha256": "09888e05c11b7ce6c51a7090f7594c0b5694595fdcfbadfabc11d7f92cb57d8d",
          "sha1": "3053dfe82bde53616606f3198581a3e05bcfdbc1",
          "md5": "f602de05fd5de2296fa433e4500167d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1-sources.jar",
          "url": "GaoShiLib-xplat-1.20.1-1.0.0-alpha.2-mc1.20.1-sources.jar",
          "size": 30769,
          "sha512": "9ce3e7ccc977b354b51510eca2b0fde380af4dfec106dfb6a0d04f1d463735641ad1c2607ead03cc97d7c97bdfaf4391e1415069b887e3023f48068c4b7c3f13",
          "sha256": "7d200f0761f273bd1445b7bc221fea4e01d70c04c45a38a543befd3602fabce3",
          "sha1": "be677c91fe3e8fd516a2d1fca94acd6f665cfaf3",
          "md5": "f64b9693b96abae3daefc6f9ad5ed702"
        }
      ]
    }
  ]
}
